<?php $this->WorldList(); ?>

<h2 class="title">Контакты</h2>

<div class="mrg-left-13">
	<p>Если вы нашли ошибку, вам не ясны детали работы какого либо инструмента ну или просто есть что сказать администрации проекта &mdash; свяжитесь с нами! Для этого есть множество способов:
	</p>
	<table class="mrg-left-157">
		<tr>
			<td class="text-middle"><div class="logo-icq"></div></td>
			<td class="bold pad-left-5">icq: </td>
			<td> 322-438-594</td>
		</tr>
		<tr>
			<td class="text-middle"><div class="logo-skype"></div></td>
			<td class="bold pad-left-5">skype: </td>
			<td> esemiko</td>
		</tr>
		<tr>
			<td class="text-middle"><div class="logo-mail"></div></td>
			<td class="bold pad-left-5">email: </td>
			<td> <a href="mailto:support@dseye.ru">support@dseye.ru</a></td>
		</tr>
		<tr>
			<td class="text-middle"><div class="logo-forum"></div></td>
			<td class="pad-left-5"><a href="http://forum.destinysphere.ru/viewtopic.php?f=33&t=217440" target="_blank" rel="nofollow">форум</a></td>
			<td> </td>
		</tr>
		<tr>
			<td class="text-middle"><div class="logo-vk"></div></td>
			<td class="pad-left-5"><a href="http://vk.com/esemi" target="_blank" rel="nofollow">вконтакта</a></td>
			<td> </td>
		</tr>
	</table>
</div>
