<?php $this->WorldList(); ?>

<h2 class="title">Контакты</h2>

<div class="mrg-left-13">
	<p>Если вы нашли ошибку, вам не ясны детали работы какого либо инструмента или просто есть, что сказать администрации проекта &mdash; свяжитесь с нами! Для этого есть множество способов:</p>
	<table class="mrg-left-157">
		<tr>
			<td class="bold pad-left-5">tlg: </td>
			<td><a href="https://t.me/esemiko" target="_blank" rel="nofollow">@esemiko</a></td>
		</tr>
		<tr>
			<td class="bold pad-left-5">email: </td>
			<td><a href="mailto:support@dseye.ru" rel="nofollow">support@dseye.ru</a></td>
		</tr>
		<tr>
			<td class="pad-left-5"><a href="http://forum.destinysphere.ru/viewtopic.php?f=33&t=217440" target="_blank" rel="nofollow">форум</a></td>
			<td> </td>
		</tr>
		<tr>
			<td class="pad-left-5"><a href="https://esemi.github.io/" target="_blank" rel="nofollow">другие средства связи</a></td>
			<td></td>
		</tr>
	</table>
</div>
