<?php $this->MainMenu('profile'); ?>

<?php $this->printMessage($this->messType, $this->messText); ?>

<div class="mrg-left-157">
	<?php
	$this->breadCrumb( array(
		sprintf('<a href="%s">Профиль</a>', $this->url(array(), 'userProfile', true)),
		'смена пароля'), false);
	?>

	<form class="mrg-top-34 mrg-left-13" method="POST">
		<table class="inline-block text-bottom mrg-right-21">
			<tbody>
				<tr>
					<td><label for="oldpass" >Старый пароль:</label></td>
					<td><input id="oldpass" class="mrg-left-5 w-157" type="password" name="oldpass" placeholder="Введите старый пароль"/></td>
				</tr>
				<tr>
					<td><label for="pass" class=" mrg-top-7">Новый пароль</label></td>
					<td><input  id="pass" class="mrg-left-5 w-157 mrg-top-7" placeholder="Введите новый пароль" type="password" name="pass"/></td>
				</tr>
				<tr>
					<td><label for="repass" class="mrg-top-7">Ещё разок</label></td>
					<td><input id="repass" class="mrg-left-5 w-157 mrg-top-7" placeholder="Повторите новый пароль" type="password" name="repass"/></td>
				</tr>
			</tbody>
		</table>
		<input  type="submit" name="сменить" value="сменить" class="inline-block text-bottom"/>
		</table>
	</form>
</div>