<?php $this->WorldList(); ?>

<h2 class="title inline">Восстановление пароля</h2>

<?php $this->printMessage($this->messType, $this->messText); ?>

<div class="mrg-left-157 mrg-top-13 mrg-right-42">
	<p>
		Если вы забыли пароль от личного кабинета, просто введите ваши имя пользователя и email указанный при регистрации, и мы вышлем вам инструкцию по восстановлению пароля.
	</p>
	<p>
		Если вы потеряли контроль над данным email адресом <a href="<?php $this->url(array(),'staticContacts', true); ?>" target="_blank">свяжитесь с нами</a>.
	</p>

	<form class="mrg-top-34 mrg-left-13" name="loginform" action="" method="post">
		<table class="inline-block text-bottom mrg-right-21">
			<tbody>
				<tr>
					<td><label for="login" >Введите логин: </label></td>
					<td><input id="login" class="mrg-left-5 w-157" name="login"  placeholder="Введите логин" type="text" value="<?php echo $this->escape($this->login); ?>" maxlength="50"  /></td>
				</tr>
				<tr>
					<td><label for="email" class=" mrg-top-7">Введите email: </label></td>
					<td><input id="email" class="mrg-left-5 w-157 mrg-top-7" name="email"  placeholder="Введите email" type="text" value="<?php echo $this->escape($this->email); ?>" maxlength="255"  /></td>
				</tr>
			</tbody>
		</table>
		<div style="margin-bottom: 13px; margin-top: 10px; width: 400px;">
			<?php echo $this->recaptcha->getHTML(); ?>
		</div>
		<input class="mrg-left-13" type="submit" value="Отправить запрос" />
	</form>
</div>


