<?php $this->WorldList(); ?>

<h2 class="title inline">Подтверждение восстановления пароля</h2>

<?php $this->printMessage($this->messType, $this->messText); ?>

<div class="mrg-left-157 mrg-top-13 mrg-right-42">
	<p>
		Если вы действительно хотите восстановить пароль от аккаунта, введите код активации, высланный на указанный вами при регистрации почтовый ящик.
	</p>

	<form class="mrg-top-21 mrg-left-13" name="loginform" action="" method="get">
		<table class="inline-block text-bottom mrg-right-21">
			<tbody>
				<tr>
					<td><label>Код активации: </label></td>
					<td><input name="token" class="mrg-left-5 w-157"  placeholder="Введите код активации" type="text" value="<?php echo $this->escape($this->token); ?>" maxlength="150"  /></td>
				</tr>
			</tbody>
		</table>
		<input class="mrg-left-5" type="submit" value="Сбросить пароль" />
	</form>
</div>


