Игрок <a target="_blank" class="<?php echo $this->RaseColor($this->player['id_rase'], true); ?> no-underline" href="<?php echo $this->url(array( 'idW' => $this->player['id_world'], 'idP' => $this->player['id'] ), 'playerStat', true) ?>">
    <?php echo $this->player['nik']; ?>
</a>&nbsp;<?php echo $this->allianceLink($this->player['id_world'], $this->player['idA'], $this->player['all'], true); ?> был удалён из мониторинга
