Здравствуйте, <b><?php echo $this->escape($this->login); ?></b>!
<br><br>
Вы успешно восстановили пароль от личного кабинета на сайте <a href='<?php echo $this->url(array(), 'staticIndex', true); ?>' target='_blank'><?php echo $this->url(array(), 'staticIndex', true); ?></a>.
<br>
===================================
<br>
Новый пароль: <b><?php echo $this->pass; ?></b>
<br>
===================================
<br><br>
--
<br>
С уважением, Администрация DSeye.ru
<br>
<a href='<?php echo $this->url(array(), 'staticIndex', true); ?>' target='_blank'><?php echo $this->url(array(), 'staticIndex', true); ?></a>