Здравствуйте, <b><?php echo $this->escape($this->login); ?></b>!
<br><br>
Вы получили это письмо, поскольку был сделан запрос на восстановление вашего пароля от личного кабинета на сайте <a href='<?php echo $this->url(array(), 'staticIndex', true); ?>' target='_blank'><?php echo $this->url(array(), 'staticIndex', true); ?></a>.
<br><br>
Если вы не делали такого запроса, просто проигнорируйте это сообщение.
<br><br>
Если же вы в самом деле забыли свой пароль, вам необходимо подтвердить сброс старого пароля.
Для этого перейдите по следующей <a href='<?php echo $this->url(array(), 'staticPasswordRememberActivate', true) . "?token={$this->token}"; ?>' target='_blank'>ссылке</a>.
Подтверждение произойдёт автоматически.
<br><br>
Если таким способом сбросить пароль не удалось, попробуйте сделать это вручную.
Пройдите по <a href="<?php echo $this->url(array(), 'staticPasswordRememberActivate', true); ?>" target='_blank'>ссылке</a> и введите указанный ниже код активации (не пароль!) в соответствующее поле.
<br>
===================================<br>
Код активации: <b><?php echo $this->token; ?></b><br>
===================================<br>
После успешного сброса старого пароля вам на почту придёт письмо с новым паролем.
<br>
Данный код активации действителен в течении <?php echo $this->scavProp; ?> часов.
<?php echo $this->partial('Partials/mail/footer-part.phtml'); ?>