<h2 class="title mrg-left-21">Глобальный поиск игроков</h2>
<div class="mrg-left-42">
	<div>
		<p class="color-logo"><span class="bold">Введите часть ника или названия домашней соты</span> (минимум 3 символа)</p>
		<input  placeholder="Введите ник или его часть"  class="js-search-term js-form-focus w-192"  type="text" value=""/>
		<table class="hide table mrg-top-13 js-table-select">
			<thead class="text-center">
				<tr>
					<th>№</th>
					<th>Ник</th>
					<th>Альянс</th>
					<th colspan="2">Дом</th>
					<th>Статус</th>
					<th>Мир</th>
				</tr>
			</thead>
			<tfoot class="border text-center">
				<tr>
					<td colspan="7">
						<span class="mrg-left-5 mrg-right-5">Результаты поиска ограничены <?php echo $this->limitFast; ?> игроками</span>
					</td>
				</tr>
			</tfoot>
			<tbody class="js-search-result">
			</tbody>
		</table>
	</div>
</div>