<?php $this->WorldList(); ?>

<h2 class="title">Форматер красной кнопки</h2>

<div class=" mrg-right-42 mrg-left-157 text-just">
	<p>
		С помощью данного калькулятора вы можете рассчитать время раунда между двумя армиями известного продовеса.<br>
		В форме ниже введите <strong class="bold">значения веса армий в продовом эквиваленте</strong> и выберите мир (в различных мирах установлены различные настройки минимального/максимального времени боя).
	</p>

	<textarea rows="5" cols="50" placeholder="Введите текст красной кнопки"></textarea>
	<input type="submit" value="форматировать" name="format" class="js-redbutton-formater-submit" />
	<div class="js-redbutton-formater-result"></div>
</div>


